name: Artifacts Downloader

on:
  push:
    branches:
      - "4.3-release-artifacts"
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-downloader:
    runs-on: ubuntu-latest
    environment: TOKENS   # required for GH_TOKEN secret

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (jq, curl)
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Make script executable
        run: chmod +x artifacts-downloader.sh

      - name: Run artifacts downloader
        run: ./artifacts-downloader.sh ${{ secrets.GH_TOKEN }}

      - name: Upload 4.3-artifacts as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: 4.3-artifacts
          path: 4.3-artifacts/